FROM node:16-alpine AS build
WORKDIR /app
COPY package.json yarn.lock ./
RUN yarn install 
COPY . .
RUN yarn build
#---------------------------------
# Stage 2: Production
FROM node:16-alpine
WORKDIR /app
COPY --from=build /app/dist .
EXPOSE 3000
CMD [ "yarn" ,"serve"]
